ARG RUST_TOOLCHAIN=1.89.0
FROM docker.io/rust:$RUST_TOOLCHAIN-trixie AS builder

ARG PROFILE
ARG VERSION
# Switch to snapshot repository to pin dependencies
RUN sed -i '/^# http/{N;s|^# \(http[^ ]*\)\nURIs: .*|# \1\nURIs: \1|}' /etc/apt/sources.list.d/debian.sources
RUN set -eux; \
    apt-get -o Acquire::Check-Valid-Until=false update; \
    apt-get install -y --no-install-recommends libjemalloc-dev mold ca-certificates curl gnupg gpgv lsb-release pkg-config; \
    if ! apt-get install -y --no-install-recommends clang-21 llvm-21 llvm-21-dev libclang-21-dev libpolly-21-dev; then \
        install -d /etc/apt/keyrings; \
        curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | gpg --dearmor -o /etc/apt/keyrings/llvm-archive-keyring.gpg; \
        codename="$(. /etc/os-release && echo "${VERSION_CODENAME}")"; \
        echo "deb [signed-by=/etc/apt/keyrings/llvm-archive-keyring.gpg] https://apt.llvm.org/${codename}/ llvm-toolchain-${codename}-21 main" > /etc/apt/sources.list.d/llvm.list; \
        apt-get -o APT::Key::gpgvcommand=/usr/bin/gpgv update; \
        apt-get install -y --no-install-recommends clang-21 llvm-21 llvm-21-dev libclang-21-dev libpolly-21-dev; \
    fi; \
    rm -rf /var/lib/apt/lists/*
ENV LLVM_SYS_210_PREFIX=/usr/lib/llvm-21
ENV LLVM_SYS_180_PREFIX=/usr/lib/llvm-21
ENV LLVM_CONFIG_PATH=/usr/lib/llvm-21/bin/llvm-config
ENV LIBCLANG_PATH=/usr/lib/llvm-21/lib
ENV PATH="/usr/lib/llvm-21/bin:${PATH}"
WORKDIR /app
COPY . .
RUN RUSTFLAGS_REPRODUCIBLE_EXTRA="-Clink-arg=-fuse-ld=mold" make build-reth-reproducible && \
  PROFILE=${PROFILE:-reproducible} VERSION=$VERSION make build-deb-x86_64-unknown-linux-gnu

FROM scratch AS artifacts
COPY --from=builder /app/target/x86_64-unknown-linux-gnu/reproducible/reth /reth
COPY --from=builder /app/target/x86_64-unknown-linux-gnu/reproducible/*.deb /

FROM gcr.io/distroless/cc-debian13:nonroot-239cdd2c8a6b275b6a6f6ed1428c57de2fff3e50
COPY --from=artifacts /reth /reth
EXPOSE 30303 30303/udp 9001 8545 8546
ENTRYPOINT [ "/reth" ]
